src/pages/Home/ResultGroup/ResultGroupCells.tsx
src/pages/Home/ResultGroup/ResultGroupRow.tsx

Fix a bug where run would not update when tags are updated

fix:Real time updates for run tags on frontpage

---

src/components/LogList/index.tsx
src/types.ts
src/utils/date.ts

Adds timestamps to log lines in the task page.

feat: logs timestamp

---

src/pages/Task/components/TaskDetails.tsx
src/translations/en.ts

- [ x] Unit tests related to the change have been updated 
- [x ] Documentation related to the change has been updated 
Minor string edits
-
-
-
Updated error messages when an artifact can't be displayed.

Minor tweaks to the messages for artifacts and task metadata

---

src/pages/Home/Home.utils.ts
src/pages/Home/index.tsx

Make home page to remember settings that were most recently used.

feat:Remember home settings over sessions

---

src/pages/Home/index.tsx

Fix runtime error on home page

hotfix:Home state runtime error

---

src/pages/Task/__tests__/AttemptSelector.test.cypress.tsx
src/pages/Task/components/AttemptSelector.tsx

Show attempt id correctly in attempt selector.

fix:Show attempt number correctly on attempt selector

---

src/hooks/useLogData/index.ts

Log fetching kept polling for new logs every 10seconds after task is finished if there was no logs.

fix:Prevent infinite post polling for logs in case of no logs

---

src/components/GenericError/index.tsx
src/components/Icon/index.tsx
src/pages/Task/components/ArtifactTable.tsx
src/translations/en.ts

Changes error ids used for translating known errors to be actual classnames of exceptions raised by the backend, instead of relying on rewritten custom identifiers.
Requires a corresponding change PR from the ui_backend. See https://github.com/Netflix/metaflow-service/pull/261

feat: use known error classes as ids

---

src/components/Button/index.tsx
src/pages/Home/ResultGroup/ResultGroupTags.tsx
src/translations/en.ts

Fixes few small issues with UI:
- Update error texts
- Make home button also look disabled when its disabled
- Fix issue with expanding tag field on home page. Tags are now clickable

Fix/minor UI fixes

---

docs/deployment.md

Added missing links for Cloudformation templates and upcoming Admin docs regarding complete Metaflow UI production stack deployment.

Added Cloudformation and Admin docs links to deployment.md

---

src/components/Tabs/index.tsx
src/components/TaskListingHeader/TaskListingHeader.tsx
src/pages/Task/components/AttemptSelector.tsx
src/pages/Task/components/TaskSection.tsx

Make tabs component scrollable horizontally when all tabs dont fit to screen.

feat:Make tabs horizontally on scrollable when low on space

---

docs/README.md

Added some docs to run metaflow-ui locally with metaflow-service
- Added docs for local deployment

readme-update

---

docs/plugin-system.md
plugin-api/README.md
plugin-api/dev/plugins/dev-plugin/index.html

Slight updates to plugin documentation

docs:Updates to plugin docs

---

plugin-api/Examples/hello-task-details/README.md
plugin-api/Examples/hello-task-details/manifest.json
plugin-api/Examples/hello-task-details/plugin.html

Add example of using subscribeToMetadata and subscribeToRunMetadata functions in plugins.

docs:Add task details plugin example

---

docs/plugin-guide.md
docs/plugin-system.md

Add step by step guide for plugin development

docs:Add step by step plugin development guide

---

src/components/DAG/DAGUtils.ts
src/components/DAG/__tests__/DAGContent.test.cypress.tsx
src/components/DAG/components/DAGContent.tsx

Fix DAG node types used for rendering the DAG.

fix: update DAG node types

---

CONTRIBUTING.md
RELEASE.md

- [ x] Documentation related to the change has been updated 
Add instructions to update the UI version in `metaflow-service` with each release.
Add instructions to update the UI version in `metaflow-service` with each release.

Include instructions for metaflow-service

---

package.json
src/components/MFCard/CardIframe.tsx

Fixes #74 
Cards hosted on different domains from MFGUI were not being shown with a height because of browser security settings. this change adds a postMessage listener for a `PluginHeightCheck` (to be consistent with plugins) message from the card iframe which tells MFGUI what height the card is.
This fix requires a change to metaflow cards to add something like (naïvely)
const resize = () => {
const body = document.body;
const height = Math.max(body.scrollHeight, body.offsetHeight, body.clientHeight);
window.parent.postMessage({ name: window.name, type: 'PluginHeightCheck', height: height }, '*');
} …

Set Card Height for cross-domain cards

---

src/pages/Task/index.tsx

More robust checking of the DAG result. A user reported javascript errors when the DAG data was not returned correctly. This change stops the whole page from failing in this case.
\-
May mask bad DAG data.
If there is bad DAG data from the backed, the task page should still render, without a complete DAG.
More robust error checking for DAG data.

Better checking of DAG result

---

.github/workflows/codeql.yml

Introduce CodeQL for static analysis

feature: add CodeQL for scanning

---

docs/plugin-guide.md
docs/plugin-system.md
plugin-api/README.md
src/components/AppBar/__tests__/AppBar.test.cypress.tsx
src/components/AppBar/index.tsx
src/components/ConnectionStatus/index.tsx
src/components/Plugins/PluginGroup.tsx
src/components/Plugins/PluginManager.tsx
src/components/Structure/index.tsx

Adding another plugin location: `header`. This plugin location is underneath the logo in the header.
\-
A plugin that is too large could upset the layout of the page.
* Set the `PLUGINS` environment variable
`export PLUGINS='{"header_plugin":{"parameters":{"sandbox":"allow-popups allow-popups-to-escape-sandbox allow-top-navigation"}}}'`
* See the plugin at the bottom of the header
Add `header` plugin location

Added new plugin

---

src/components/Collapsable/index.tsx
src/components/MFCard/CardIframe.tsx
src/components/MFCard/useTaskCards.ts
src/components/Timeline/useTaskData.ts
src/components/Timeline/useTaskListSettings.ts
src/hooks/useLogData/index.ts
src/hooks/useSearchField/index.ts
src/pages/Run/RunPage.tsx
src/pages/Task/index.tsx
src/translations/en.ts

Previously, a task page would try to show task id and card hash combinations that did not exist because the task id would be stale. This change aligns card data with the task that it was requested for, in order to avoid mismatches.
I considered refactoring the code so that the Task component did not re-render so many time. I made some progress.
Possibility of regressions.
* Go to a task page for a task with cards
* Click on new tasks on the left side of the page
* Check in the network tab to see that there have not been any requests for task id/hash combinations that do not exist
Prevent requests for mismatched task ids and …

Added spinner and error message to the iframe

---

package.json

Bump version to 1.3.10

---

src/pages/Task/components/TaskDetails.tsx

The duration for a task in the Task View was not updating unless the user scrolled the pane. This change auto-updates the duration.
\-
\-
* Start a long-running task
* Navigate to the task page
* Observe that the duration updates
Make task duration auto-update

Make task duration auto-update

---

package.json

bump version to 1.3.11

---

Dockerfile
docs/feature-flags.md
plugin-api/MetaflowPluginAPI.js
src/components/Collapsable/__tests__/Collapsable.test.cypress.tsx
src/components/Collapsable/index.tsx
src/components/Icon/index.tsx
src/components/MFCard/DynamicCardIframe.tsx
src/components/Plugins/PluginGroup.tsx
src/constants.ts

Reconciliation with outerbounds `metaflow-ui`
* Upgrade node version to 20
* Visual changes to plugin and collapsable menus
* Removed duplicate functions in plugin code
* Improvements to Dynamic Cards
\-
\-
\-
Reconciliation with outerbounds version

Reconcile from obp

---

src/pages/Home/ResultGroup/ResultGroupTags.tsx

Sort the user tags alphabetically
\-
\-
* Add multiple user tags to a run
* Ensure that they are displayed in alphabetical order in the `Tags` column on the MFGUI homepage
Sort user tags

Sort user tags

---

src/components/Breadcrumb/index.tsx
src/components/Collapsable/index.tsx
src/components/Popover/index.tsx
src/components/Tabs/index.tsx
src/components/TitledRow/index.tsx
src/mocks/browser.js
src/pages/Run/components/RunWarning.tsx
src/pages/Task/components/AnchorMenu.tsx
src/pages/Task/components/AnchoredView.tsx
src/pages/Task/components/TaskList.tsx
src/pages/Task/components/TaskListRow.tsx
src/pages/Task/index.tsx
src/theme/theme.css

Add theming to many other components

feat: Update theming for various components

---

src/pages/Task/index.tsx

[logs] increase page size 

---

package.json

release: 1.3.14

---

.github/workflows/package.yml

upload-artifact v2 has been deprecated. updating this to v4

fix: update GHA upload-artifact to v4
