src/components/Breadcrumb/index.tsx

Fix a bug where breadcrumb flow filter would not work in some cases due home page now remembering previous settings.

fix:Make breadcrumb flow filter to work

---

src/components/SearchField/index.tsx

Add loader to artifact search input field.

fix:Add loader to artifact search bar

---

src/hooks/useSearchField/index.ts

Fixed artifact search loader disappearing too early. Search functionality wasnt used to progress messages.

fix:Artifact search stopping loader too early

---

.gitignore
cypress/integration/debug.js
cypress/integration/home.js
cypress/integration/notifications.js
cypress/integration/run_details.js

Update current full UI tests to pass with some mocked data. These tests were initially planned for e2e testing, but they are currently not run by any CI. We should consider if they are useful at all since UI have quite a coverage with component tests.

tests:Update UI tests to pass with mock data

---

src/utils/VERSION.ts

Server versions request was missing catch from it which could cause crash. This would not cause much of a difference anyways since if server is not responding UI won't work.

fix:Add missing catch from service version request

---

yarn.lock

Ran `npx browserslist@latest --update-db` to update `can-i-use`. This was to suppress a warning in the output when building
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
Run `yarn build` and see that there is no warning for `can-i-use`.
Updated `can-i-use` database

Updated can-i-use database

---

src/pages/Task/index.tsx

The problem was that the `aside` (left nav) of the card was showing when the card was displayed in MFGUI.
There is a corresponding change to the metaflow card-generating code that checks for the `embed` parameter and adds a class to the HTML that already triggers CSS to hide the `aside`.
Sending a post message to achieve this seemed overkill.
I looked into having the CSS detect whether it was embedded, without javascript but could not find a solution.
Users may like the aside and see that what is displayed in MFGUI is different from the downloaded card (which will show the aside with a wider screen)
* Run a flow with the changes in https://github.com/Netflix/metaflow/pull/877 e.g. `python3 dummyflow.py run --with card`
* Navigate to the task in MFGUI
* Ensure that the `aside` is not shown …

Added `embed` parameter to iframe src so that the `aside` is not shown

---

src/components/HelpMenu/TimezoneSelector.tsx
src/components/TimezoneProvider/index.tsx

Fix a bug with daylight saving times. They were not applied as they should.

fix:Daylight savings time not being applied for timezones

---

src/pages/Home/Home.utils.ts

Fixing issue #54. Desired tag was getting replaced by cached values

fix: Replacing tags correctly when arriving from run page

---

src/components/MFCard/__tests__/useTaskCards.test.cypress.tsx
src/components/MFCard/useTaskCards.ts
src/components/TitledSection/index.tsx
src/pages/Task/components/AnchorMenu.tsx
src/pages/Task/components/AnchoredView.tsx
src/pages/Task/components/TaskSection.tsx
src/pages/Task/index.tsx
src/translations/en.ts

Adds a status to the return value from the `useTaskCards()` hook so that the status can show in the UI.
More visual noise on the page.
* Load MFGUI
* Start a flow with a number of tasks (preferably slow)
* Navigate to a recently started task in MFGUI
* Note the "loading" indicators
* Note the card appearing
---
* Bork your `metaflow-service` (e.g. by switching to a branch that doesn't support cards)
* Load MFGUI
* Start a flow with a number of tasks (preferably slow)
* Navigate to a recently started task in MFGUI
* Note the "loading" indicators
* Note the card timeout message
Shows status when loading cards

Add status to card loading

---

src/components/MFCard/CardIframe.tsx

A bug was found where some cards were not showing.
The cause was found to be cards with a `<body>` with an absolute position that gave the `offsetHeight` as 0. So the code that set the iframe size for the card set to to 0.
The fix was to use the maximum of the `offsetHeight`, `clientHeight`, and `scrollHeight` instead. This is consistent with how plugin iframes set their size.
* Generate a card with a body with an absolute position. 
* `NBFlow/6070/end/130917` is an example.
* Make sure the card is visible
Fixed zero-height iframe for cards

Use maximum height of iframe

---

src/pages/Run/RunPage.tsx

The _parameters step typically does not contain all the metadata
associated with the other steps. This fix simply fetches metadata
from the `start` step instead.

Fetch run metadata on the start step and not the _parameters one.

---

plugin-api/MetaflowPluginAPI.js
plugin-api/__tests__/pluginapi.test.cypress.ts

To fix https://github.com/Netflix/metaflow-ui/issues/67
The `setVisibility()` function relied on matching the plugin with the name and the slot. The `MetaflowPluginAPI.js` code was setting the name but not the slot. This change sets the slot as well.
I considered a larger re-write as there are a few things, like the data structure containing `config` twice.
None considered
See steps in https://github.com/Netflix/metaflow-ui/issues/67
Fix: connects slot in MetaflowPluginAPI.js to fix `setVisibility()`

fix: assigning slot to global plugin variable

---

src/components/Plugins/PluginRegisterSystem.tsx

The issue was that, when there were multiple plugins for a slot, sometimes one of them would not be registered.
* The plugins to appear are set by a `PLUGINS` env variable and read by `metaflow-service`.
* `metaflow-service` reads the `PLUGINS` variable and loads the plugins' code and checks their validity.
* The plugins' information is sent to `metaflow-ui` via a request to `/plugins`.
* `metaflow-ui` makes requests to `metaflow-service` to get the plugins' code.
* The plugins' codes are added in iframes to a hidden element on the page.
* The code in the iframes sends a postMessage to the window to register the plugin.
* Each registered plugin is rendered to the correct slot on the page, within an iframe and removed from the hidden element.
When a plugin was in the hidden element and …

Changed iframe key to be unique

---

src/components/FilterInput/index.tsx
src/components/MFCard/useTaskCards.ts
src/components/Tabs/index.tsx
src/hooks/useLogData/index.ts
src/pages/Home/ResultGroup/ResultGroupRow.tsx
src/pages/Task/components/AnchoredView.tsx
src/pages/Task/index.tsx
src/utils/row.ts

Fixed bug where there was an infinite loop when the first task was selected.
Prevent re-renders of the `useLogData` hook.
Removing `abort()` may mean requests that aren't needed will still continue.
* Start a new flow
* In MFGUI, click on the run
* Click on the Task tab
* When `start` appears, click on the start step
MFGUI should not lock up

Removed abort() on rerender

---

src/components/Collapsable/index.tsx

The Collapsable header has a chevron that indicates to the user that the section can be opened and closed. The chevron is aligned to the right of the screen and not very noticeable.
This change moves the chevron to the left, near the section title.
\-
\-
* Find a run on the homepage
* Click on the run
* Notice the `Details` section header has a chevron next to it
Moved collapsable section chevron to the left to make it more discoverable.

Moved collapsable chevron to left

---

src/components/MFCard/CardIframe.tsx

When a postMessage is received by the app, the source is checked against the recipient to ensure that it matches.
Fixes: https://github.com/Netflix/metaflow-ui/issues/99
Checking that the recipient is correct by using an attribute of the iframe (like name)
`e.source` may not be reliable - https://stackoverflow.com/questions/16266474/javascript-listen-for-postmessage-events-from-specific-iframe/47676007#47676007 - I did not experience this problem. If it is not reliable, the check will fail which is not a bad result as the height of the iframe will be periodically checked anyway.
1. Add a plugin to metaflow-service. You can follow the steps for a simple plugin [here](https://github.com/outerbounds/mfgui_plugins/tree/main/task_debugger)
2. Run a flow with a card `python myflow.py run --with …

fix: check sender of message to ensure correct recipient

---

src/components/Timeline/TimelineRow/LineElement.tsx

Added the start and end times of a task to the tooltip that shows when the task is hovered in the timeline view.
This feature was requested by @romain-intel , who wanted an easier way to see the duration between tasks.
* Hovering over the gap between tasks shows a duration of the time between them
This change does not take resumed or restarted attempts into account. It only reflect the same start and end times as the timeline view.
* Go to the timeline view for a run
* Hover your mouse over a task line
* Confirm that the start and end times are the same as those shown when you click on the task
Added start and end times to timeline tooltip

Added start and end times to task tooltip

---

src/pages/Home/ResultGroup/ParametersPreview.tsx
src/pages/Home/ResultGroup/StartedAtCell.tsx
src/pages/Home/ResultGroup/TimelinePreview.tsx
src/pages/Run/RunHeader.tsx
src/pages/Run/RunPage.tsx
src/pages/Task/index.tsx

Reverts parts of #76 as subscriptions to resource updates over the web socket require passing in `run_number` instead of `run_id`. The user visible parts should remain using `run_id` when available.
Addresses #102
Fixes issue with realtime updates in timeline for runs with `run_id`

fix: realtime timeline updates for runs with run_id

---

src/App.tsx
src/constants.ts

Extend existing functionality with REACT_APP_BASE_PATH: previously that variable would have need to be set at compile time. This PR adds an alternative way to set it via `window.`, similar to how we treat `METAFLOW_SERVICE` setting

allow to modify base path at runtime

---

src/components/Form/TimeRange.tsx
src/hooks/useResource/__tests__/useResource.test.cypress.tsx
src/pages/Home/Content/index.tsx
src/pages/Home/Home.utils.ts
src/pages/Home/Sidebar/SidebarTimerangeSelection.tsx
src/pages/Home/index.tsx

The Time Range preset filters were not working. The time range was always set back to the default (30 days) after selection.
This change removes two pieces of code that reset the time range to the default.
\-
The removed code may have been deliberately added for some needed functionality. Or it could have been included to paper over race conditions and React indeterminacy.
This change does not fix existing bugs with the Back button and loaders showing when they shouldn't be.
* Load the homepage
* Click on the Time Range filter
* Select `Today`
* Click on `Set`
You should see the results filtered for Today only.
The other presets can be tested in the same way.
Fix bug with Time Range presets not working

Removed code that overwrites time settings

---

src/components/Form/Checkbox.tsx
src/components/Timeline/TaskListLabel.tsx
src/components/Timeline/useTaskData.ts
src/pages/Debug/index.tsx

Fix for [#129 ](https://github.com/Netflix/metaflow-ui/issues/129)
The bug occurred when the row already existed in memory and the statuses were assigned to the status of the last task. As the last task was failing in this case, all steps were given a failing status.
The bug in this case was that the object passed to the function that calculated the status for a step was the wrong object. The object should have only contained the current step, instead of all the steps.
The fix was to pass the expected object to the status function.
Additionally, changes were made to the left column of the timeline to align step and task names better
The status of debug fields is not shown as
\-
\-
Run a flow like the following, that deliberately fails on the last step
```
from metaflow import FlowSpec, …
```

Step status color not always correct #129

---

src/components/Plugins/PluginManager.tsx
src/components/Plugins/__tests__/plugins.test.cypress.ts

Add version to the path so that the browser cache is busted and the latest plugin is always downloaded.
A random number in the path to always bust the cache. The downside of this approach is that the HTML request would never be cached. The implemented approach will cache most of the time yet will download a new version when the version number is changed in the config for the plugin.
Plugin developers may not update the version number in the config.
* Ensure that the URL for the iframe for the plugin includes the version
Add version to the plugin URL to bust the cache when the version changes

Add version to plugin URL to prevent caching

---

src/components/Trigger/__tests__/Trigger.test.cypress.tsx
src/components/Trigger/index.tsx

Changes an `a` element to a `Link` component for the trigger link so that the link respects the basename set on Router. This fixes a bug where the `REACT_APP_BASE_PATH` env variable was set but the trigger link did not include it.
\-
\-
* Set `REACT_APP_BASE_PATH`
* Find a run that was triggered by another run
* Click on the trigger link at the top of the page and ensure the `REACT_APP_BASE_PATH` value is at the start of the URL
Change `a` to `Link` for trigger link

Use Link instead of a

---

src/pages/Task/components/SectionLoader.tsx

Set the minimum height of the log section when loading, showing errors, and showing content. This will prevent the size of the section changing when logs are loading, which caused the content below to "bounce".
\-
\-
* Run a longish running flow
* Navigate to a task
* Observe the size of the log sections. They should not change until log data fills them up
Set minimum height of log section

Set min-height even when showing log content

---

src/components/MFCard/DynamicCardIframe.tsx
src/components/MFCard/useTaskCards.ts
src/constants.ts

- make refresh interval default smaller
- remove timeout code block in card load
- leveraging the `created_on` timestamps in dataupdates to discard stale data
- handle case of idle refresh
Changes compatible with : https://github.com/Netflix/metaflow-service/pull/417

[cards] performance optimizations

---

src/pages/Task/components/TaskList.tsx

> I don’t know if this is just me but if you have a long list of tasks and you are in the timeline view and then select a task to view in the task view, while it remembers what task you selected it presents the list of task back at the top (so if you selected something after scrolling, you have to scroll again to get to it. It doesn’t do this when you are already in task view
This change scrolls the list so that the active task is visible in the task list.
https://github.com/Netflix/metaflow-ui/assets/93726128/8b558d8b-6517-4f23-ac30-3b3584ffcc18
I considered capturing the index of the clicked task when it was clicked in the timeline view, storing that value somewhere, and using that value to scroll to the correct place in the task list. The approach that I used was simpler.
The task …

Scroll to active index in task list

---

src/components/Form/Dropdown.tsx

Fix dropdowns going multiline when they should not.

fix: disable dropdown multiline wrapping
